name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push client
        uses: docker/build-push-action@v5
        with:
          context: proxy
          push: true
          tags: ghcr.io/alexbidenko/proxy-dns/proxy-application:latest

  deploy:
    runs-on: ubuntu-22.04

    needs: [build]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -t rsa ${{ secrets.PROXY_SERVER_SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.PROXY_SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy 🚀
        run: docker stack deploy --prune --with-registry-auth -c proxy/compose.yaml proxy-service
        env:
          DOCKER_HOST: ssh://${{ secrets.PROXY_SERVER_SSH_USER }}@${{ secrets.PROXY_SERVER_SSH_HOST }}
