name: deploy dns

on:
  push:
    branches:
      - main

jobs:
  build-application:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'dns/**'

      - if: steps.changes.outputs.src == 'true'
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.changes.outputs.src == 'true'
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - if: steps.changes.outputs.src == 'true'
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: dns
          push: true
          tags: ghcr.io/alexbidenko/proxy-dns/dns-application:latest

  build-caddy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'dns/**'

      - if: steps.changes.outputs.src == 'true'
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.changes.outputs.src == 'true'
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - if: steps.changes.outputs.src == 'true'
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: dns/caddy
          push: true
          tags: ghcr.io/alexbidenko/proxy-dns/dns-caddy:latest

  deploy:
    runs-on: ubuntu-22.04

    needs: [build-application, build-caddy]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -t rsa ${{ secrets.DNS_SERVER_SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.DNS_SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy 🚀
        run: |
          env PROXY_SERVER_ADDRESS=${{ secrets.PROXY_SERVER_ADDRESS }} \
          env PROXY_SERVER_ADDRESS_IPV6=${{ secrets.PROXY_SERVER_ADDRESS_IPV6 }} \
          env LOCATION_SERVER_ORIGIN=${{ secrets.LOCATION_SERVER_ORIGIN }} \
          env UPSTREAM_DNS=${{ secrets.UPSTREAM_DNS }} \
            docker stack deploy --prune --with-registry-auth -c dns/compose.yaml dns-service
        env:
          DOCKER_HOST: ssh://${{ secrets.DNS_SERVER_SSH_USER }}@${{ secrets.DNS_SERVER_SSH_HOST }}
